# Generated by Django 4.2.6 on 2023-11-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_delete_ticket'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype', verbose_name='ticket')),
            ],
        ),
    ]
