# Generated by Django 4.2.6 on 2023-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='forget_password_token',
            field=models.UUIDField(default=None, null=True, unique=True, verbose_name='forget_password_token'),
        ),
    ]
